In [1]:
from sympy import *
from sympy.plotting import plot3d
init_printing(use_unicode=False, wrap_line=False, no_global=True)
import numpy as np

In [2]:
#1
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
transposed_m = [[matrix_A[j][i] for j in range(len(matrix_A))] for i in range(len(matrix_A[0]))]
transposed_m

[[1, 4], [2, 5], [3, 6]]

In [5]:
a2, a1 = symbols('a2, a1')

In [6]:
#2
MSE = 1/4 * (((a1 * 1 + a2 * 2 ) - 5)**2 + \
             ((a1 * 5 + a2 * 3 ) - 6)**2 + \
             ((a1 * 2 + a2 * 4 ) - 10)**2 + \
             ((a1 * 3 + a2 * 7 ) - 8)**2)
MSE

In [16]:
MSE_a1 = diff(MSE, a1)
MSE_a1

In [17]:
MSE_a2 = diff(MSE, a2)
MSE_a2

In [31]:
#1)
MSE.subs({a1: 0, a2: 0})

In [32]:
MSE_a1_00 = MSE_a1.subs({a1: 0, a2: 0})
MSE_a1_00

In [24]:
MSE_a2_00 = MSE_a2.subs({a1: 0, a2:0})
MSE_a2_00

In [35]:
grad_00 = np.array([MSE_a1_00, MSE_a2_00])
grad_00

array([-39.5000000000000, -62.0000000000000], dtype=object)

In [26]:
anti_grad_00 = grad_00*(-1)
anti_grad_00

array([39.5000000000000, 62.0000000000000], dtype=object)

In [27]:
step1 = anti_grad_00 * 0.01
step1

array([0.395000000000000, 0.620000000000000], dtype=object)

In [28]:
point1 = np.array([0, 0])
point1

array([0, 0])

In [29]:
point2 = point1 + step1
point2

array([0.395000000000000, 0.620000000000000], dtype=object)

In [30]:
#2)
MSE.subs({a1: 0.395, a2: 0.62})

In [33]:
MSE_a1_0395_062 = MSE_a1.subs({a1: 0.395, a2: 0.62})
MSE_a1_0395_062

In [36]:
MSE_a2_0395_062 = MSE_a2.subs({a1: 0.395, a2: 0.62})
MSE_a2_0395_062

In [38]:
grad_0395_062 = np.array([MSE_a1_0395_062, MSE_a2_0395_062])
grad_0395_062

array([-17.5375000000000, -28.7350000000000], dtype=object)

In [39]:
anti_grad_0395_062 = grad_0395_062 * -1
anti_grad_0395_062

array([17.5375000000000, 28.7350000000000], dtype=object)

In [40]:
step2 = anti_grad_0395_062 * 0.01
step2

array([0.175375000000000, 0.287350000000000], dtype=object)

In [44]:
point3 = point2 + step2
point3

array([0.570375000000000, 0.907350000000000], dtype=object)

In [45]:
#3)
MSE.subs({a1: 0.570375, a2: 0.90735})

In [46]:
MSE_a1_057_0907 = MSE_a1.subs({a1: 0.570375, a2: 0.90735})
MSE_a1_057_0907

In [47]:
MSE_a2_057_0907 = MSE_a2.subs({a1: 0.570375, a2: 0.90735})
MSE_a2_057_0907

In [49]:
grad_057_0907 = np.array([MSE_a1_057_0907, MSE_a2_057_0907])
grad_057_0907

array([-7.50863750000000, -13.4947250000000], dtype=object)

In [50]:
anti_grad_057_0907 = grad_057_0907 * -1
anti_grad_057_0907

array([7.50863750000000, 13.4947250000000], dtype=object)

In [51]:
step3 = anti_grad_057_0907 * 0.01
step3

array([0.0750863750000000, 0.134947250000000], dtype=object)

In [52]:
point4 = point3 + step3
point4

array([0.645461375000000, 1.04229725000000], dtype=object)

In [53]:
#4)
MSE.subs({a1: 0.645461375, a2: 1.04229725})

In [54]:
MSE_a1_064_1042 = MSE_a1.subs({a1: 0.645461375, a2: 1.04229725})
MSE_a1_064_1042

In [62]:
MSE_a2_064_1042 = MSE_a2.subs({a1: 0.645461375, a2: 1.04229725})
MSE_a2_064_1042

In [56]:
grad_064_1042 = np.array([MSE_a1_064_1042, MSE_a2_064_1042])
grad_064_1042

array([-2.94066643750000, -6.50479562499999], dtype=object)

In [57]:
anti_grad_064_1042 = grad_064_1042 * -1
anti_grad_064_1042

array([2.94066643750000, 6.50479562499999], dtype=object)

In [58]:
step4 = anti_grad_064_1042 * 0.01
step4

array([0.0294066643750000, 0.0650479562499999], dtype=object)

In [60]:
point5 = point4 + step4
point5

array([0.674868039375000, 1.10734520625000], dtype=object)

In [61]:
#5)
MSE.subs({a1: 0.674868039375, a2: 1.10734520625})

In [63]:
MSE_a1_067_1107 = MSE_a1.subs({a1: 0.674868039375, a2: 1.10734520625})
MSE_a1_067_1107

In [64]:
MSE_a2_067_1107 = MSE_a2.subs({a1: 0.674868039375, a2: 1.10734520625})
MSE_a2_067_1107

In [65]:
grad_067_1107 = np.array([MSE_a1_067_1107, MSE_a2_067_1107])
grad_067_1107

array([-0.871133488437501, -3.29157205062500], dtype=object)

In [66]:
anti_grad_067_1107 = grad_067_1107 * -1
anti_grad_067_1107

array([0.871133488437501, 3.29157205062500], dtype=object)

In [67]:
step5 = anti_grad_067_1107 * 0.01
step5

array([0.00871133488437501, 0.0329157205062500], dtype=object)

In [68]:
point6 = point5 + step5
point6

array([0.683579374259375, 1.14026092675625], dtype=object)

In [69]:
#6)
MSE.subs({a1: 0.683579374259375, a2: 1.14026092675625})