In [89]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd

data = pd.read_csv('3.10_non_linear.csv')
data.head()

x_train   y_train
0  0.138368  0.838812
1  0.157237  0.889313
2  0.188684  1.430040
3  0.685553  1.717309
4  0.874237  2.032588

In [90]:
X_ex = np.array([data['x_train']]).reshape(-1, 1)
# for el in X_ex:
#     one_arr = np.array([1])
#     X_1 = np.append(one_arr, el)
#     X = np.array([X_1])
#     print(X)
X = np.insert(X_ex, 0, 1, axis=1)
X

array([[1.        , 0.13836845],
       [1.        , 0.15723687],
       [1.        , 0.18868424],
       [1.        , 0.68555275],
       [1.        , 0.87423699],
       [1.        , 1.18242126],
       [1.        , 1.25160548],
       [1.        , 1.27047391],
       [1.        , 1.40255288],
       [1.        , 1.42771078],
       [1.        , 1.4717371 ],
       [1.        , 1.53463185],
       [1.        , 1.55350027],
       [1.        , 1.84281611],
       [1.        , 2.01892141],
       [1.        , 2.28936882],
       [1.        , 2.64157941],
       [1.        , 2.68560573],
       [1.        , 2.79881628],
       [1.        , 2.82397418],
       [1.        , 2.91202682],
       [1.        , 2.92460577],
       [1.        , 3.27052689],
       [1.        , 3.31455321],
       [1.        , 3.52839535],
       [1.        , 3.59757958],
       [1.        , 3.76110592],
       [1.        , 3.77368487],
       [1.        , 3.91834279],
       [1.        , 4.10702703],
       [1.

In [106]:
Y = np.array([data['y_train']]).reshape(-1, 1)
Y

array([[ 0.83881243],
       [ 0.88931326],
       [ 1.43003955],
       [ 1.7173094 ],
       [ 2.03258831],
       [ 1.86034102],
       [ 1.87892766],
       [ 2.43001534],
       [ 2.32785552],
       [ 2.20364916],
       [ 2.20770757],
       [ 1.38803901],
       [ 1.71854419],
       [ 2.1032645 ],
       [ 2.29517686],
       [ 1.96515239],
       [ 0.74594859],
       [ 1.16079805],
       [ 0.8472635 ],
       [ 0.75558457],
       [ 1.3045932 ],
       [ 1.06644218],
       [ 0.67694404],
       [ 0.57916634],
       [ 0.13337461],
       [ 0.17123457],
       [ 0.1961104 ],
       [-0.07201584],
       [ 0.11811017],
       [ 0.46667278],
       [ 0.31561051],
       [ 0.21494492],
       [ 0.05031305],
       [ 0.10614754],
       [ 0.05713164],
       [-0.05725158],
       [ 0.44923374],
       [-0.33611985],
       [-0.03823668],
       [ 0.09524973],
       [ 0.31302894],
       [-0.23125656],
       [ 0.02493584],
       [ 0.41871855],
       [ 0.16572723],
       [ 0

In [117]:
from numpy.linalg import inv
from sklearn.linear_model import LinearRegression

In [134]:
class CustomLinearReg:
    def __init__(self):
        pass
    
    def fit(self, x, y):
        W = inv((x.T).dot(x)).dot(x.T).dot(y)
        return W
    
    def predict(self, x):
        reg = LinearRegression().fit(x, Y)
        y_pred = reg.predict(x)
        return y_pred

In [135]:
model = CustomLinearReg()

In [136]:
model.fit(X, Y)

array([[ 1.96903541],
       [-0.33531472]])

In [137]:
model.predict(X)

array([[ 1.92263843],
       [ 1.91631157],
       [ 1.9057668 ],
       [ 1.73915947],
       [ 1.67589087],
       [ 1.57255215],
       [ 1.54935366],
       [ 1.5430268 ],
       [ 1.49873878],
       [ 1.49030296],
       [ 1.47554029],
       [ 1.45445075],
       [ 1.44812389],
       [ 1.35111203],
       [ 1.29206133],
       [ 1.20137633],
       [ 1.08327494],
       [ 1.06851226],
       [ 1.0305511 ],
       [ 1.02211529],
       [ 0.99258994],
       [ 0.98837203],
       [ 0.87237959],
       [ 0.85761691],
       [ 0.78591249],
       [ 0.76271401],
       [ 0.70788121],
       [ 0.70366331],
       [ 0.65515738],
       [ 0.59188877],
       [ 0.59188877],
       [ 0.58556191],
       [ 0.56447238],
       [ 0.51596645],
       [ 0.44637098],
       [ 0.43582621],
       [ 0.41895459],
       [ 0.41262772],
       [ 0.31350691],
       [ 0.25023831],
       [ 0.23969354],
       [ 0.20595028],
       [ 0.18907865],
       [ 0.15322644],
       [ 0.14268168],
       [ 0

In [118]:
reg = LinearRegression().fit(X, Y)

In [124]:
reg.predict(X)

array([[ 1.92263843],
       [ 1.91631157],
       [ 1.9057668 ],
       [ 1.73915947],
       [ 1.67589087],
       [ 1.57255215],
       [ 1.54935366],
       [ 1.5430268 ],
       [ 1.49873878],
       [ 1.49030296],
       [ 1.47554029],
       [ 1.45445075],
       [ 1.44812389],
       [ 1.35111203],
       [ 1.29206133],
       [ 1.20137633],
       [ 1.08327494],
       [ 1.06851226],
       [ 1.0305511 ],
       [ 1.02211529],
       [ 0.99258994],
       [ 0.98837203],
       [ 0.87237959],
       [ 0.85761691],
       [ 0.78591249],
       [ 0.76271401],
       [ 0.70788121],
       [ 0.70366331],
       [ 0.65515738],
       [ 0.59188877],
       [ 0.59188877],
       [ 0.58556191],
       [ 0.56447238],
       [ 0.51596645],
       [ 0.44637098],
       [ 0.43582621],
       [ 0.41895459],
       [ 0.41262772],
       [ 0.31350691],
       [ 0.25023831],
       [ 0.23969354],
       [ 0.20595028],
       [ 0.18907865],
       [ 0.15322644],
       [ 0.14268168],
       [ 0