In [2]:
import pandas as pd

In [3]:
train_df = pd.read_csv('train.csv')
train_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [283]:
train_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [4]:
train_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
train_df['Age'] = train_df.groupby(['Sex']).Age.apply(lambda x: x.fillna(x.median()))
train_df.to_csv('agewithout_nan.csv')
train_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  27.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [6]:
train_df[['Cabin','Embarked']] = train_df[['Cabin','Embarked']].fillna('U')

In [7]:
train_df[['Cabin','Embarked']]

Cabin Embarked
0       U        S
1     C85        C
2       U        S
3    C123        S
4       U        S
..    ...      ...
886     U        S
887   B42        S
888     U        S
889  C148        C
890     U        Q

[891 rows x 2 columns]

In [8]:
train_df['PassengerId'][6:20]

6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
Name: PassengerId, dtype: int64

In [9]:
train_df['Sex'] = train_df['Sex'].apply(lambda x: 0 if (x == 'male') else 1) 

In [10]:
train_df['Embarked'] = train_df['Embarked'].apply(lambda x: 0 if x == 'U' else (1 if x == 'S' else (2 if x == 'C' else 3)))

In [11]:
train_df = train_df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X = train_df.drop(['Survived'],axis=1).values
y = train_df['Survived'].values

In [14]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)


In [15]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [16]:
knn = KNeighborsClassifier(n_neighbors=5)
knn_model = knn.fit(x_train, y_train)
knn_pred = knn.predict(x_test)

In [17]:
nb = GaussianNB()
nb_model = nb.fit(x_train, y_train)
nb_pred = nb.predict(x_test)

In [18]:
dtc = DecisionTreeClassifier()
dtc_model = dtc.fit(x_train, y_train)
dtc_pred = dtc.predict(x_test)

In [19]:
lr = LogisticRegression()
lr_model = lr.fit(x_train, y_train)
lr_pred = lr.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix, recall_score
from sklearn.metrics import precision_score

In [21]:
confusion_knn = confusion_matrix(y_test, knn_pred)
confusion_knn

array([[110,  21],
       [ 47,  45]], dtype=int64)

In [37]:
rec_score = recall_score(y_test, knn_pred)
rec_score

0.4891304347826087

In [38]:
pres_score = precision_score(y_test, knn_pred)
pres_score

0.6818181818181818

In [28]:
from sklearn.metrics import f1_score

In [29]:
fscore = 2 * pres_score * rec_score / (pres_score + rec_score)
fscore

0.5696202531645569

In [30]:
f1_score(y_test, knn_pred)

0.5696202531645569

In [32]:
from sklearn.metrics import precision_recall_fscore_support, classification_report

In [33]:
precision_recall_fscore_support(y_test, knn_pred)

(array([0.70063694, 0.68181818]),
 array([0.83969466, 0.48913043]),
 array([0.76388889, 0.56962025]),
 array([131,  92], dtype=int64))

In [36]:
print(classification_report(y_test, knn_pred))

              precision    recall  f1-score   support

           0       0.70      0.84      0.76       131
           1       0.68      0.49      0.57        92

    accuracy                           0.70       223
   macro avg       0.69      0.66      0.67       223
weighted avg       0.69      0.70      0.68       223



In [49]:
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import roc_auc_score
import numpy as np

In [41]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=17)

In [46]:
c_s = np.logspace(-1, 2, 500)
c_s

array([  0.1       ,   0.10139395,   0.10280732,   0.1042404 ,
         0.10569346,   0.10716676,   0.10866061,   0.11017528,
         0.11171107,   0.11326826,   0.11484715,   0.11644806,
         0.11807128,   0.11971713,   0.12138593,   0.12307798,
         0.12479362,   0.12653318,   0.12829698,   0.13008537,
         0.13189869,   0.13373729,   0.13560151,   0.13749172,
         0.13940828,   0.14135156,   0.14332192,   0.14531975,
         0.14734543,   0.14939935,   0.15148189,   0.15359347,
         0.15573448,   0.15790533,   0.16010645,   0.16233824,
         0.16460115,   0.1668956 ,   0.16922204,   0.1715809 ,
         0.17397264,   0.17639773,   0.17885662,   0.18134978,
         0.1838777 ,   0.18644085,   0.18903974,   0.19167485,
         0.19434669,   0.19705578,   0.19980263,   0.20258777,
         0.20541173,   0.20827506,   0.2111783 ,   0.21412202,
         0.21710676,   0.22013311,   0.22320165,   0.22631296,
         0.22946764,   0.23266629,   0.23590953,   0.23

In [62]:
roc_auc = roc_auc_score(y_train, knn.predict_proba(x_train)[:, 1])

In [66]:
clf = LogisticRegressionCV(Cs=c_s, cv=skf, random_state=0)
clf.fit(x_train, y_train)
clf.predict(x_train)

D:\ana\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\ana\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\ana\l

array([0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,

In [306]:
confusion_nb = confusion_matrix(y_test, nb_pred)
confusion_nb

array([[111,  20],
       [ 27,  65]], dtype=int64)

In [310]:
recall_score(y_test, nb_pred)

0.7065217391304348

In [307]:
confusion_dtc = confusion_matrix(y_test, dtc_pred)
confusion_dtc

array([[114,  17],
       [ 26,  66]], dtype=int64)

In [311]:
recall_score(y_test, dtc_pred)

0.717391304347826

In [308]:
confusion_lr = confusion_matrix(y_test, lr_pred)
confusion_lr

array([[114,  17],
       [ 28,  64]], dtype=int64)

In [312]:
recall_score(y_test, lr_pred)

0.6956521739130435

In [314]:
from sklearn.metrics import precision_score

In [315]:
precision_score(y_test, dtc_pred)

0.7951807228915663