# The `NumPy` Library: Part 2


###  1
Load array from file `array_hw.npy` and save it as `arr`. The array contains the sales volumes of ice cream (in pieces) in 5 stores for one week in June (7 days, from Monday to Sunday). In tasks 2-5, you need to work with the `arr` array.


In [3]:
### YOUR CODE HERE ###
import numpy as np

arr = np.load('array_hw.npy')
print(arr)

[[100  80  70  60 120]
 [ 65  55  20  50  60]
 [ 80  90  75  80  60]
 [ 45  60  70  20  40]
 [ 82  47  56  89  92]
 [115 120 113 106 107]
 [ 46  74  23  34  19]]


###  2
Thinking of the `arr` array as a table, the table currently has stores in columns (1 store = 1 column, 5 in total) and days in rows (1 day = 1 row, 7 in total). Convert the `arr` array so that the rows are stores and the columns are days (1 row = 1 store). Save changes. Check if the shape of the array has changed.


In [10]:
### YOUR CODE HERE ###
import numpy as np

arr = np.load('array_hw.npy')
arr_shape =arr.shape
arr_transp = arr.transpose()
arr_transp_shape = arr_transp.shape
print(arr_shape, '\n', arr_transp, '\n',arr_transp_shape)

(7, 5) 
 [[100  65  80  45  82 115  46]
 [ 80  55  90  60  47 120  74]
 [ 70  20  75  70  56 113  23]
 [ 60  50  80  20  89 106  34]
 [120  60  60  40  92 107  19]] 
 (5, 7)


###  3

Let's imagine that the sales information is updated: it turned out that the fifth store on Sunday sold not 19 servings of ice cream, but 25, and the second store sold not 55 servings of ice cream, but 65 on Tuesday. Change the `arr` array according to this information.


In [11]:
### YOUR CODE HERE ###
arr_transp[4][6] = 25
arr_transp[1][1] = 65
print(arr_transp)

[[100  65  80  45  82 115  46]
 [ 80  65  90  60  47 120  74]
 [ 70  20  75  70  56 113  23]
 [ 60  50  80  20  89 106  34]
 [120  60  60  40  92 107  25]]


###  4

Calculate the total sales of ice cream for all stores.

In [5]:
### YOUR CODE HERE ###
arr_transp = arr.transpose()
print(arr_transp.sum())

2423


###  5

Download the updated `arr` array to a txt file. The txt file itself does not need to be loaded into the system, just write the appropriate code to the ipynb file.


In [6]:
### YOUR CODE HERE ###
np.savetxt('arr_transp.txt', arr_transp)

### 6
The `income` array is given, containing the values of the store's profit in thousands at the beginning, middle and end of the year, for four consecutive years (the values are not grouped in any way, we can assume that they were unloaded from the file in this way).
Reshape the array so that the values are grouped with three values in each list within the array (profit at the beginning, middle and end of the year).

In [7]:

income = np.array([1000, 2000, 3500, 
                   2500, 1500, 3800, 
                   1200, 9000, 12000,
                   4500, 6700, 11000])

In [16]:
### YOUR CODE HERE ###
income = np.array([1000, 2000, 3500, 
                   2500, 1500, 3800, 
                   1200, 9000, 12000,
                   4500, 6700, 11000])

print(income.reshape(4, 3))

[[ 1000  2000  3500]
 [ 2500  1500  3800]
 [ 1200  9000 12000]
 [ 4500  6700 11000]]


###  7
Create a `turnout` list (*list*, not an array) containing the following polling turnout percentages:

23.56, 45.78, 34.92, 57.34, 56.55, 67.23.

Create, using list includes and the non-NumPy built-in functions for rounding, a new list `turnout_r` that consists of the turnout values from `turnout` rounded to the first decimal place.


In [6]:
### YOUR CODE HERE ###
turnout = [23.56, 45.78, 34.92, 57.34, 56.55, 67.23]
turnout_r = []

turnout_r = [round(el, 1) for el in turnout]


print(turnout_r)

[23.6, 45.8, 34.9, 57.3, 56.5, 67.2]


###  8
Perform the same operations as in the previous task, but using arrays and `NumPy` functions. In other words, create an array `turnout` and based on it create an array `turnout_r` with turnout values rounded to the first decimal place.


In [18]:
### YOUR CODE HERE ###
turnout = np.array([23.56, 45.78, 34.92, 57.34, 56.55, 67.23])
turnout_r = np.around(turnout, 1)

print(turnout_r)

[23.6 45.8 34.9 57.3 56.6 67.2]


###  9

 Go to the https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9_%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81_%D1%81%D1%87%D0%B0%D1%81%D1%82%D1%8C%D1%8F Wikipedia page, select any 5 countries and any 3 indicators from the **2012 International Happiness Index** table, and create a `happy` structured array, one that has a "country name" field and fields for the three selected indicators. Choose the appropriate type for each field (measure) in the array, and keep that in mind when creating a structured array. Display the resulting array on the screen.


In [22]:
### YOUR CODE HERE ###
happy = np.array([('Norway', 51.4, 7.6, 4.8),
                  ('Brasil', 52.9, 6.8, 2.9),
                  ('Chili', 53.9, 6.6, 3.2),
                  ('Cuba', 56.2, 5.4, 1.9),
                  ('Columbia', 59.8, 6.4, 1.8)],
                 dtype=[('country name', 'U10'),
                        ('HPI', float),
                        ('life satisfaction', float),
                        ('ecological footprint', float)])

print(happy)
happy

[('Norway', 51.4, 7.6, 4.8) ('Brasil', 52.9, 6.8, 2.9)
 ('Chili', 53.9, 6.6, 3.2) ('Cuba', 56.2, 5.4, 1.9)
 ('Columbia', 59.8, 6.4, 1.8)]


array([('Norway', 51.4, 7.6, 4.8), ('Brasil', 52.9, 6.8, 2.9),
       ('Chili', 53.9, 6.6, 3.2), ('Cuba', 56.2, 5.4, 1.9),
       ('Columbia', 59.8, 6.4, 1.8)],
      dtype=[('country name', '<U10'), ('HPI', '<f8'), ('life satisfaction', '<f8'), ('ecological footprint', '<f8')])

###  10
Convert the structured array obtained in the previous task to a regular list and display its second element on the screen.


In [24]:
### YOUR CODE HERE ###
happy_converted = happy.tolist()
print(happy_converted[1])

('Brasil', 52.9, 6.8, 2.9)


.<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> 
# Additional task.

<br>

###  1

Write a `build_array()` function that takes as input the dimension of a square matrix (a two-dimensional array in which the number of rows and the number of columns are the same) and creates an identity matrix `E` (array) of the appropriate dimension. You cannot use the ready-made function `np.eye()`, you can use loops and conditional constructs.

**Example:**

Input:

    build_array(4)

Output:

    array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
       


In [2]:
### YOUR CODE HERE ###
import numpy as np
def build_array(dim):
    unit_array = np.zeros((dim, dim))
    diagonal = np.diag_indices(dim)
    unit_array[diagonal] = 1
    return unit_array
print(build_array(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


###  2

Write a function `my_reshape()` that takes an array and its new dimension (a pair of numbers) as input, and:

* if the specified dimensions are correct, then returns an array of the new dimension;
* if the specified dimensions are incorrect, then it returns an empty array (example: you cannot make a new 4×3 array from a 2×5 array, because the old array has 10 elements, and the new one has 12).

**Example:**

Input:

    A = np.array([[2, 4, 6], 
            [4, 8, 10]])

    my_reshape(A, 6, 1)

Output:

    array([[2], 
       [4], 
       [6], 
       [4], 
       [8],
       [10]])

Input:

    A = np.array([[2, 4, 6], 
            [4, 8, 10]])

    my_reshape(A, 4, 2)

Output:

    array([])

**Note:** the results in the output may be visually different (displayed without line breaks, indicating the data type), this is normal, the examples have been modified for readability.



In [9]:
### YOUR CODE HERE ###
import numpy as np
def my_reshape(arr, m, n):
    if arr.size == m * n:
        print(arr.reshape(m, n))
    else:
        arr = np.array([])
        print(arr)


my_arr = np.array([[1, 2, 4, 6],
                   [3, 6, 8, 9]])
print(my_reshape(my_arr, 4, 2))

[[1 2]
 [4 6]
 [3 6]
 [8 9]]
None
