# `NumPy` library: part 1



Given an array containing the scores of students of the English language course for the entrance exam. Listeners are divided into 15 groups of 10 people.


In [5]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

###  1

Calculate how many students received 0 for the entrance exam.


In [5]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])


count = len(scores[scores == 0])
print(count)

13


###  2

Count how many listeners scored above 50.


In [1]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])


count = len(scores[scores > 99])
print(count)

8


###  3

Calculate how many people received a score of at least 50, but not higher than 70.


In [11]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])


count = len(scores[(scores > 50) & (scores < 70)])
print(count)

20


###  4

Determine in which group the average score for the entrance exam is higher.


In [2]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

mean_value = scores.mean(axis=1)
max_value = mean_value.argmax()
print('In the group numbered', max_value + 1, 'the average score is higher')

In the group numbered 10 the average score is higher


###  5

Store listener scores above 0 in the `nonzero` array.


In [1]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

nonzero = scores[scores > 0]
print(nonzero)

[ 20  40  56  80   5  25  27  74   1  98  67 100   8  56  34  82 100   7
  78  54  23  79 100  42  95  83  51  50  47  23 100  94  25  48  38  77
  90  87  41  89  52   5  17  28  99  32  18  21  18  29  31  48  62  76
  22   6  65  78  43  22  38  88  94 100  77  28  39  41  81  45  54  98
  12  66  88  44  55 100  12  11  17  70  86  96  56  23  32  49  70  80
  20  24  76  50  29  40   3   2   5  11  33  63  28  40  51 100  98  87
  22  30  16  54  78  12  25  35  10  19  67 100  88  24  33  47  56  62
  34  77  53  50  89  70  72  56  29  15  20]


###  6

Using the `nonzero` array, determine the minimum entry score for all groups.


In [2]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

nonzero = scores[scores > 0]
print(nonzero.min())

1


###  7

Select from the `nonzero` array only those values that correspond to an advanced level of knowledge of the language - an exam score above 80. Store the result in the `advanced` array. In tasks 8-10, you need to work with the `advanced` array.


In [3]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

nonzero = scores[scores > 0]
advanced = nonzero[nonzero > 80]
print(advanced)

[ 98 100  82 100 100  95  83 100  94  90  87  89  99  88  94 100  81  98
  88 100  86  96 100  98  87 100  88  89]


###  8

Determine the dimension of the `advanced` array.


In [26]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

nonzero = scores[scores > 0]
advanced = nonzero[nonzero > 80]
print(advanced.ndim)

1


###  9

Define the shape of the `advanced` array.


In [25]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

nonzero = scores[scores > 0]
advanced = nonzero[nonzero > 80]
print(advanced.shape)

(28,)


###  10

Determine the total number of elements in the `advanced` array.


In [10]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

nonzero = scores[scores > 0]
advanced = nonzero[nonzero > 80]
print(advanced.size)

28


###  11

Based on the original `scores` array, create a boolean `sto` array, where `True` is the exam score of 100 and `False` is all other scores.


In [1]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

sto = scores == 100
print(sto)

[[False False False False False False False False False False]
 [False False False  True False False False False  True False]
 [False False False False  True False False False False False]
 [False False False False  True False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False  True]
 [False False False False False False False False False False]
 [False False False False False False False  True False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]
 [False False False False False False False False False False]]


###  12

Based on the original `scores` array, display the scores of the students in the first seven groups (inclusive, there must be 7 lists of scores).


In [2]:
### YOUR CODE HERE ###
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

form = np.resize(scores, (7, 10))
print(form)

[[ 20  40  56  80   0   5  25  27  74   1]
 [  0  98  67 100   8  56  34  82 100   7]
 [ 78  54  23  79 100   0   0  42  95  83]
 [ 51  50  47  23 100  94  25  48  38  77]
 [ 90  87  41  89  52   0   5  17  28  99]
 [ 32  18  21  18  29  31  48  62  76  22]
 [  6   0  65  78  43  22  38  88  94 100]]


.<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> 
# Additional task.
<br>


In tasks 1-2, you need to work with the array `A`:


In [ ]:
import numpy as np
A = np.array([[2, 9, 8, 0],
             [8, 7, 5, 6], 
             [3, 1, 0, 2], 
             [6, 5, 6, 8],
             [1, 0, 0, 4]])

### Task 1

Transpose array `A` without using `NumPy` built-in methods. Save the resulting array to the `A_tr` variable. It is acceptable to use loops and conditional structures (if necessary).

**Reminder:** transposition is the operation of swapping rows and columns. Example:

Before transposition:

        [[2, 5, 0], 
        [7, 8, 1]]

After transposition:

        [[2, 7],
        [5, 8],
        [0, 1]]



In [21]:
### YOUR CODE HERE ###
A = np.array([[2, 9, 8, 0],
             [8, 7, 5, 6], 
             [3, 1, 0, 2], 
             [6, 5, 6, 8],
             [1, 0, 0, 4]])

for column in range(A.shape[1]):
    A_tr = np.array(A[:, column])
    print(A_tr)

[2 8 3 6 1]
[9 7 1 5 0]
[8 5 0 6 0]
[0 6 2 8 4]


### Task 2

Compare results: check the equality of the array `A_tr` obtained above and the array obtained by transposing the array `A` using the `.T` method.




In [16]:
### YOUR CODE HERE ###
A = np.array([[2, 9, 8, 0],
             [8, 7, 5, 6], 
             [3, 1, 0, 2], 
             [6, 5, 6, 8],
             [1, 0, 0, 4]])
A_transp = A.T
arr_equal = np.array_equal(A_tr, A_transp)

print(arr_equal)

False


### Task 3

Student N moonlights as a tutor in mathematics and conducts classes of various types: he prepares for the Unified State Examination, for olympiads, “pulls up” mathematics for elementary school students.

The `classes` array stores the number of lessons taught for five working days, the `prices` array stores the cost of one lesson (we assume that a student conducts classes of the same type per day, the same cost).


Determine the student's weekly income using `.dot()` to find the dot product

In [ ]:
classes = np.array([3, 3, 2, 0, 2])
prices = np.array([1500, 1500, 2500, 1000, 1000])

In [3]:
### YOUR CODE HERE ###
import numpy as np

classes = np.array([3, 3, 2, 0, 2])
prices = np.array([1500, 1500, 2500, 1000, 1000])

print(np.dot(classes, prices))

16000


### Task 4

Based on the results of working with data on student essay marks given by two different experts, two boolean arrays `expert1` and `expert2` were created, in which the value `True` means the grade is "satisfactory" and higher, and the value `False` is unsatisfactory . A total of 15 essays were evaluated, 5 essays for each of the three topics.


In [6]:
expert1 = np.array([[True, False, False, True, True],
                   [False, True, False, False, True],
                   [True, True, True, False, False]])
expert2 = np.array([[True, False, False, False, True],
                   [False, False, False, False, False],
                   [True, False, True, False, False]])

In [7]:
### YOUR CODE HERE ###

common_values = np.logical_and(expert1, expert2)
nonzero_values = np.count_nonzero(common_values)

print(nonzero_values,'students will receive credit')

4 students will receive credit


Determine, using various logical operators (`|`, `&`, etc.) and auxiliary methods/functions, how many students will receive a credit, if it is known that for this it is necessary to receive a mark not lower than satisfactory from both experts.


### Task 5

Given an array `essay` with the final grades of students for an essay from task 4:


In [4]:


essay = np.array([["pass", "not pass", "not pass", "not pass", "pass"],
        ["not pass", "not pass", "not pass", "not pass", "not pass"],
        ["pass", "not pass", "pass", "not pass", "not pass"]])

Check the answer in the previous problem using the `essay` array. The solution must be presented as code, not as outputs from an explicit element count.


In [ ]:
### YOUR CODE HERE ###

passed_students = np.count_nonzero(essay == 'pass')
print(passed_students)

### Task 6

Using the arrays `expert1` and `expert2` from Problem 4, determine the consistency of two experts using the Jaccard closeness measure, which is calculated as follows:

$$
J(A, B) = \frac{|A \cap B|}{|A| + |B| - |A \cap B|}
,$$ 

where $A$ is the first set, $B$ is the second set, $A \cap B$ is the intersection of sets, i.e. their common elements. The notation $|A|$ means "the number of elements in the set".

The sets $A$ and $B$ in this problem are the sets (groups) of students who received credit from the first and second experts.

In [8]:
### YOUR CODE HERE ###
exp1_passed = np.count_nonzero(expert1)
exp2_passed = np.count_nonzero(expert2)
common_values = np.count_nonzero(np.logical_and(expert1, expert2))
jaccard_value = common_values/(exp1_passed + exp2_passed-common_values)

print(jaccard_value)

0.5
